spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buysell
    username: root
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
    show-sql: true
    open-in-view: false
